### ISSUE TITLE
Feature request: Being able to skip initialization of Piwik

### ISSUE THREAD

**Issue by swergas** [joernroeder/piwik-react-router#41]
Hi

Our web app [assembl](https://github.com/assembl/assembl) adds dynamically a piwik tracking script to the DOM of its pages, if an administrator has activated piwik tracking and has provided a piwik site id in the administration panel.

So, as we are progressively migrating our application to React, we would like to use piwik-react-router to track user navigation in React routes, but using an already initialized Piwik tracking script.

I think this solution is better than a solution where we would try to get our piwik configuration data from our application server and then use this data to initialize piwik-react-router.

And I see no other solution than these 2 for now.

Do you have any ideas about this type of use case? I will provide a pull request with the changes we made to skip piwik initialization.

Edit: I provided a PR here: https://github.com/joernroeder/piwik-react-router/pull/42

**Comment by joernroeder** [comment]
Hey @swergas,
thanks for opening the issue and submitting the pull request! 

Currently i see the following use cases:
- a piwik script is already injected and instantiated from a third-party into the page (this is your case)
- multiple react component trees are present on a single page (a static website with e.g. a dynamic react based search solution and a react based comment system) and both component trees are using a shared piwik instance to track their events.

the second case could be done by:
1. inject and instantiate piwik from the outside (your case again) and setting the appropriate options in `piwik-react-router`
2. dynamically test if a piwik instance already exists and create or use it depending on the result of the test. An option/flag like `injectScript` or `alreadyInitialized` should therefore test for a) piwik.js script is present and b) inspecting the `window._paq` Object to test if it's a valid piwik instance or not.

Of couse we have to deal with async initialization of piwik itself but by doing the test fully dynamically instead of setting boolean options my second use-case wouldn't depend on a pre-instantiated piwik instance and component tree which is initialized first could set up piwik as well.

This are just some ideas i had when i saw your fork and the changes you made. what do you think?

**Comment by joernroeder** [comment]
closing this in favor of #43
